// Code generated by Kitex v0.4.4. DO NOT EDIT.

package relationdomainservice

import (
	"context"
	relationDomain "github.com/TremblingV5/DouTok/kitex_gen/relationDomain"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddRelation(ctx context.Context, Req *relationDomain.DoutokAddRelationRequest, callOptions ...callopt.Option) (r *relationDomain.DoutokAddRelationResponse, err error)
	RmRelation(ctx context.Context, Req *relationDomain.DoutokRmRelationRequest, callOptions ...callopt.Option) (r *relationDomain.DoutokRmRelationResponse, err error)
	ListRelation(ctx context.Context, Req *relationDomain.DoutokListRelationRequest, callOptions ...callopt.Option) (r *relationDomain.DoutokListRelationResponse, err error)
	CountRelation(ctx context.Context, Req *relationDomain.DoutokCountRelationRequest, callOptions ...callopt.Option) (r *relationDomain.DoutokCountRelationResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRelationDomainServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRelationDomainServiceClient struct {
	*kClient
}

func (p *kRelationDomainServiceClient) AddRelation(ctx context.Context, Req *relationDomain.DoutokAddRelationRequest, callOptions ...callopt.Option) (r *relationDomain.DoutokAddRelationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddRelation(ctx, Req)
}

func (p *kRelationDomainServiceClient) RmRelation(ctx context.Context, Req *relationDomain.DoutokRmRelationRequest, callOptions ...callopt.Option) (r *relationDomain.DoutokRmRelationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RmRelation(ctx, Req)
}

func (p *kRelationDomainServiceClient) ListRelation(ctx context.Context, Req *relationDomain.DoutokListRelationRequest, callOptions ...callopt.Option) (r *relationDomain.DoutokListRelationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListRelation(ctx, Req)
}

func (p *kRelationDomainServiceClient) CountRelation(ctx context.Context, Req *relationDomain.DoutokCountRelationRequest, callOptions ...callopt.Option) (r *relationDomain.DoutokCountRelationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CountRelation(ctx, Req)
}
