// Code generated by MockGen. DO NOT EDIT.
// Source: ./kitex_gen/favorite/favoriteservice/client.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	favorite "github.com/TremblingV5/DouTok/kitex_gen/favorite"
	callopt "github.com/cloudwego/kitex/client/callopt"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// FavoriteAction mocks base method.
func (m *MockClient) FavoriteAction(ctx context.Context, Req *favorite.DouyinFavoriteActionRequest, callOptions ...callopt.Option) (*favorite.DouyinFavoriteActionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, Req}
	for _, a := range callOptions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FavoriteAction", varargs...)
	ret0, _ := ret[0].(*favorite.DouyinFavoriteActionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FavoriteAction indicates an expected call of FavoriteAction.
func (mr *MockClientMockRecorder) FavoriteAction(ctx, Req interface{}, callOptions ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, Req}, callOptions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FavoriteAction", reflect.TypeOf((*MockClient)(nil).FavoriteAction), varargs...)
}

// FavoriteCount mocks base method.
func (m *MockClient) FavoriteCount(ctx context.Context, Req *favorite.DouyinFavoriteCountRequest, callOptions ...callopt.Option) (*favorite.DouyinFavoriteCountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, Req}
	for _, a := range callOptions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FavoriteCount", varargs...)
	ret0, _ := ret[0].(*favorite.DouyinFavoriteCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FavoriteCount indicates an expected call of FavoriteCount.
func (mr *MockClientMockRecorder) FavoriteCount(ctx, Req interface{}, callOptions ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, Req}, callOptions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FavoriteCount", reflect.TypeOf((*MockClient)(nil).FavoriteCount), varargs...)
}

// FavoriteList mocks base method.
func (m *MockClient) FavoriteList(ctx context.Context, Req *favorite.DouyinFavoriteListRequest, callOptions ...callopt.Option) (*favorite.DouyinFavoriteListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, Req}
	for _, a := range callOptions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FavoriteList", varargs...)
	ret0, _ := ret[0].(*favorite.DouyinFavoriteListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FavoriteList indicates an expected call of FavoriteList.
func (mr *MockClientMockRecorder) FavoriteList(ctx, Req interface{}, callOptions ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, Req}, callOptions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FavoriteList", reflect.TypeOf((*MockClient)(nil).FavoriteList), varargs...)
}

// IsFavorite mocks base method.
func (m *MockClient) IsFavorite(ctx context.Context, Req *favorite.DouyinIsFavoriteRequest, callOptions ...callopt.Option) (*favorite.DouyinIsFavoriteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, Req}
	for _, a := range callOptions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IsFavorite", varargs...)
	ret0, _ := ret[0].(*favorite.DouyinIsFavoriteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFavorite indicates an expected call of IsFavorite.
func (mr *MockClientMockRecorder) IsFavorite(ctx, Req interface{}, callOptions ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, Req}, callOptions...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFavorite", reflect.TypeOf((*MockClient)(nil).IsFavorite), varargs...)
}
