version: "3"

volumes:
    redis_vol:
    mysql_vol:

networks:
    total:
        driver: bridge

services:
    redis:
        image: redis:latest
        command: redis-server /etc/redis/redis.conf
        networks:
            - total
        volumes:
            - redis_vol:/data
            - ./redis.conf:/etc/redis/redis.conf
        ports:
            - "6379:6379"
        restart: always

    mysql:
        image: mysql:8.0
        env_file:
            - ./.env
        networks:
            - total
        volumes:
            - mysql_vol:/var/lib/mysql:rw
            - ./my.cnf:/etc/mysql/my.cnf
        ports:
            - "3307:3307"
        restart: always

    etcd:
        image: quay.io/coreos/etcd
        container_name: etcd
        networks:
            - total
        command: etcd -name etcd -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380
        ports:
            - "2379:2379"
            - "2380:2380"
        restart: always
