// Code generated by Kitex v0.4.4. DO NOT EDIT.

package messagedomainservice

import (
	"context"
	messageDomain "github.com/TremblingV5/DouTok/kitex_gen/messageDomain"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddMessage(ctx context.Context, Req *messageDomain.DoutokAddMessageRequest, callOptions ...callopt.Option) (r *messageDomain.DoutokAddMessageResponse, err error)
	ListMessage(ctx context.Context, Req *messageDomain.DoutokListMessageRequest, callOptions ...callopt.Option) (r *messageDomain.DoutokListMessageResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMessageDomainServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMessageDomainServiceClient struct {
	*kClient
}

func (p *kMessageDomainServiceClient) AddMessage(ctx context.Context, Req *messageDomain.DoutokAddMessageRequest, callOptions ...callopt.Option) (r *messageDomain.DoutokAddMessageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddMessage(ctx, Req)
}

func (p *kMessageDomainServiceClient) ListMessage(ctx context.Context, Req *messageDomain.DoutokListMessageRequest, callOptions ...callopt.Option) (r *messageDomain.DoutokListMessageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListMessage(ctx, Req)
}
