Global:
  Source: "config(local)"
  ChangeMe: "v1"

JWT:
  signingKey: "signingKey"

Etcd:
  Address: "localhost"
  Port: 2379

Server:
  Name: "DouTokFavoriteDomainServer"
  Address: "127.0.0.1"
  Port: 8092

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1"

Snowflake:
  Node: 602

MySQL:
  Host: "localhost"
  Port: 3306
  Username: "admin"
  Password: "root"
  Database: "DouTok"
  CharSet: "utf8mb4"
  ParseTime: true
  loc: "Local"

Redis:
  Host: "localhost"
  Port: 6379
  Password: "root"
  FavCache:
    Num: 3
  FavCntCache:
    Num: 4
  FavTotalCountCache:
    Num: 8


Kafka:
  Broker: "localhost:9092"

Otel:
  Host: "82.156.171.8"
  Port: 4317