Global:
  Source: "config(local)"
  ChangeMe: "v1"

Etcd:
  Address: "localhost"
  Port: 2379

Server:
  Name: "DouTokMessageDomainServer"
  Address: "127.0.0.1"
  Port: 8091

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1.1"

Snowflake:
  Node: 10

Hbase:
  Host: "localhost"
  Table: "message"
  MessageNum: 50

Redis:
  Host: "localhost"
  Port: 6379
  Password: "root"
  DataBases:
    Default: 5

Kafka:
  Brokers:
    - "192.168.2.120:9092"
  Topics:
    - "message_1"
#    - "message_2"
  GroupIds:
    - "message01"
    - "message02"
    - "message03"
    - "message04"
    - "message05"

Otel:
  Host: "82.156.171.8"
  Port: 4317