Global:
  Source: "config(local)"
  ChangeMe: "v1"

JWT:
  signingKey: "signingKey"

Etcd:
  Address: "localhost"
  Port: 2379

Server:
  Name: "DouTokUserDomainServer"
  Address: "127.0.0.1"
  Port: 8100
  Argon2ID:
    Memory: 64*1024
    Iterations: 3
    Parallelism: 2
    SaltLength: 16
    keyLength: 32

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1.1"

Snowflake:
  Node: 40

MySQL:
  Host: "localhost"
  Port: 3306
  Username: "admin"
  Password: "root"
  Database: "DouTok"
  CharSet: "utf8mb4"
  ParseTime: true
  loc: "Local"

Otel:
  Host: "82.156.171.8"
  Port: 4317