package constants

const (
	API_SERVER_NAME             = "API"
	COMMENT_SERVER_NAME         = "COMMENT"
	COMMENT_DOMAIN_SERVER_NAME  = "COMMENT_DOMAIN"
	FAVORITE_SERVER_NAME        = "FAVORITE"
	FAVORITE_DOMAIN_SERVER_NAME = "FAVORITE_DOMAIN"
	FEED_SERVER_NAME            = "FEED"
	MESSAGE_SERVER_NAME         = "MESSAGE"
	MESSAGE_DOMAIN_SERVER_NAME  = "MESSAGE_DOMAIN"
	PUBLISH_SERVER_NAME         = "PUBLISH"
	RELATION_SERVER_NAME        = "RELATION"
	RELATION_DOMAIN_SERVER_NAME = "RELATION_DOMAIN"
	USER_SERVER_NAME            = "USER"
	USER_DOMAIN_SERVER_NAME     = "USER_DOMAIN"
	VIDEO_DOMAIN_SERVER_NAME    = "VIDEO"
)
