version: '3'

networks:
  total:
    driver: bridge

services:
  redis:
    image: redis:latest
    command: redis-server /etc/redis/redis.conf
    networks:
        - total
    volumes:
        - ./redis_data:/data
        - ./config/redis.conf:/etc/redis/redis.conf
    ports:
        - "6379:6379"
    restart: always

  mysql:
    image: mysql:8.0
    env_file:
        - ./config/.env
    networks:
        - total
    volumes:
        - ./mysql_data:/var/lib/mysql:rw
        - ./config/my.cnf:/etc/mysql/my.cnf
    ports:
        - "3306:3306"
    restart: always

  etcd:
    image: quay.io/coreos/etcd
    container_name: etcd
    networks:
        - total
    command: etcd -name etcd -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380
    ports:
        - "2379:2379"
        - "2380:2380"
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    networks:
        - total
    volumes:
        - ./zk_data:/opt/zookeeper-3.4.6/data
    container_name: zookeeper
    ports:
        - "2180:2181"
        - "2182:2182"
    restart: always

  hbase:
    build: ./hbase
    container_name: hbase
    hostname: hb-master
    networks:
        - total
    ports:
        - "16000:16000"
        - "16010:16010"
        - "16020:16020"
        - "16030:16030"
        - "16201:16201"
        - "9090:9090"
        - "9095:9095"
        - "2181:2181"
    volumes:
        - ./hbase-data:/hbase-data
        - ./hbase-zoo-data:/zookeeper-data
    environment:
        - HBASE_CONF_hbase_cluster_distributed=false
    restart: always

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    networks:
        - total
    depends_on:
        - hbase
    ports:
        - "9092:9092"
    volumes:
        - ./kafka_data:/kafka
    environment:
        - KAFKA_BROKER_ID=0
        - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.119:9092
        - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_HEAP_OPTS=-Xmx512M -Xms16M
    restart: always

  kafka-ui:
    image: leixuewen/kafka-ui-lite
    networks:
        - total
    ports:
        - 8889:8889
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ':9001' /data
    ports:
        - "9000:9000"
        - "9001:9001"
    environment:
        MINIO_ACCESS_KEY: root
        MINIO_SECRET_KEY: rootroot
    volumes:
      - ./minio_data:/data
      - ./config/minio:/root/.minio
    privileged: true
    restart: always
