name: Check Golang Code

on:
  pull_request:
    branches: ["main"]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1

      - uses: reviewdog/action-golangci-lint@v2
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--timeout 10m --exclude-use-default=false"
          level: "error"
          reporter: github-pr-check
          filter_mode: nofilter

      # - name: gofumpt -s with reviewdog
      #   env:
      #     REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     go install mvdan.cc/gofumpt@v0.2.0
      #     gofumpt -e -d . | \
      #     reviewdog -name="gofumpt" -f=diff -f.diff.strip=0 -reporter=github-pr-review
