name: Unit Test for Golang Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Run coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
